### ISSUE TITLE
Add (debug/initialization) printouts data to example

### ISSUE THREAD

**Issue by baskapteijn** [Erriez/ErriezDHT22#8]
When the example starts you want to know if the defines are properly set for your board. f.e. add this to the init:

#if defined ARDUINO_ESP8266_NODEMCU
    Serial.println("This is an ESP8266\n");
#endif

And offcourse for all other supported boards.

The same applies to PIN selection.

**Comment by Erriez** [comment]
According to the Arduino specifications, macro's should not be used in examples. I'm aware of violating this rule, because macro's are used in my automatic build environment to support multiple targets.

There are many ESP8266 flavors on the market to create macro's for each board.  The ARDUINO_BOARD macro works for the ESP8266, but is not available for every board:
Serial.println(F(ARDUINO_BOARD " DHT22 temperature and humidity sensor example\n"));

Prints:
"ESP8266_NODEMCU DHT22 temperature and humidity sensor example"

I'd like to keep the macro's to a minimum for simplicity, but you can add it yourself. Use the F() macro to put strings in flash (AVR targets).
